name: PHP Code Quality

on:
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      - name: "Composer Install dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "Check PHP-CS-Fixer coding standards"
        if: ${{ matrix.php-version != '8.4' }}
        run: composer run-script cs:dry-run

      - name: "Run PHPStan"
        run: composer run-script analyse

      - name: "Run test suite (with coverage)"
        run: composer run-script test:unit:coverage
        env:
          XDEBUG_MODE: coverage

      - name: "Validate test coverage"
        uses: "5monkeys/cobertura-action@v14"
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        with:
          path: coverage/coverage.xml
          minimum_coverage: 90
          skip_covered: false
          fail_below_threshold: 90
          only_changed_files: true
          show_class_names: true
          show_missing: true
